import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen flex flex-col items-center justify-center animate-spin"
      >
        <header>
          <h1>React & Next.js</h1>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/route">Rota</Link>
            <Link href="/caracteristicas">Caracteristicas</Link>
          </nav>
        </header>
        <main className="bg-purple-500 w-[70vw] min-h-[60vw] flex flex-col justify-center items-center">
          {children}
        </main>

        <footer>DIW</footer>
      </body>
    </html>
  );
}
