import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Relogio from "../componentes/relogio/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen flex flex-col items-center justify-center"
      >
        <header className="flex flex-col justify-center items-center">
          <h1>React & Next.js</h1>
          <nav>
            <Link href="/" className="p-2">Home</Link>
            <Link href="/tecnologiasCard" className="p-2">Tecnologias</Link>
            <Link href="/Projetos" className="p-2">Projetos</Link>
            <Link href="/contador" className="p-2">Contador</Link>
            <Link href="/input" className="p-2">Input</Link>
            <Link href="/produtos" className="p-2">DeisiShop</Link>
            
          </nav>
        </header>
        <main className="bg-purple-500 w-[90vw] min-h-[60vw] flex flex-col justify-center items-center rounded-md p-7">
          {children}
        </main>

        <footer>
          <p>DIW</p>
          <Relogio />
        </footer>
      </body>
    </html>
  );
}
